In [1]:
import numpy as np
import pandas as pd
from numpy.random import randn

In [4]:
np.set_printoptions(precision = 2)

In [5]:
a = np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
b = np.array([[10,20,30],[4,9,16]])
b

array([[10, 20, 30],
       [ 4,  9, 16]])

In [8]:
np.random.seed(25)

In [11]:
c = 36*np.random.randn(9)

In [12]:
c

array([-22.32,  66.16, -73.92,  31.27, -33.15,  -8.36,  77.51, -48.05,
         2.75])

In [13]:
d = np.arange(1,35)

In [14]:
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [15]:
a+10

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [17]:
a+c

array([-21.32,  68.16, -70.92,  35.27, -28.15,  -2.36,  84.51, -40.05,
        11.75])

In [21]:
aa = np.array([[2,4,5],[1,3,5],[11,22,33]])
aa

array([[ 2,  4,  5],
       [ 1,  3,  5],
       [11, 22, 33]])

In [22]:
bb = np.array([[1,2,3],[4,5,6],[7,8,9]])
bb

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
aa + bb

array([[ 3,  6,  8],
       [ 5,  8, 11],
       [18, 30, 42]])

In [24]:
np.dot(aa,bb)

array([[ 53,  64,  75],
       [ 48,  57,  66],
       [330, 396, 462]])